<main class="main-about">
    <h3 class="title-about">À propos de nous</h3>
    <section class="about">
        <div class="image-about"><img src="../images/istockphoto-1320932798-612x612.jpg" alt=""></div>

        <div class="aboutUs">
            <h3>Des produits à l'image de la France</h3>
            <p>
                Nous sommes une petite entreprise proche de nos entrepreneurs,
                producteurs et agriculteurs français. Nous avons à cœur de proposer des
                produits de qualité et une rémunération qui récompense le travail de nos
                producteurs français. Nos marges ont été réduites au maximum pour que
                nos clients payent un prix moins élevé tout en respectant nos
                engagements sur la qualité et la provenance de tous nos produits.
            </p>
        </div>
    </section>

    <section class="our-artisans">
        <div>
            <div class="image"><img src="../images/slide-armano-artisan-ceinturier-camargue.jpg" alt=""></div>
            <div class="image"><img src="../images/istockphoto-582273084-612x612.jpg" alt=""></div>
        </div>
        <div>
            <p>Nous travaillons avec plus d'une vingtaine d'artisans et petites entreprises partout en France : <strong>Matthieu</strong>,
                ébéniste en Corrèze ; <strong>Brod O Bord</strong>, notre brodeur en Provence ;<strong> Valence
                    Services</strong>, notre confectionneur dans la Drôme; <strong>Eric</strong>, notre forgerons dans
                la Somme, etc..</p>
            <div><img src="../images/carte.png" alt=""></div>
        </div>
    </section>
</main>