<main class="main-connection">

    <form action="" method="POST" class="formulaire">

        <label for="">Email</label>
        <input type="email" name="email" placeholder="Exemple@hotmail.fr" required>

        <label for="">Mot de passe</label>
        <input type="password" name="password" required>


        <button type="submit" value="connexion">Se connecter</button>
        <p>Pas encore inscrit ? Inscrivez-vous <a href="<?= url('/inscription') ?>">ici</a></p>
    </form>
</main>